services:
  db:
    image: postgres:16-alpine
    container_name: cols-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - cols_pgdata:/var/lib/postgresql/data
    networks:
      - cols-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cols_user -d cols_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cols-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cols-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${APP_DATABASE_URL}
    container_name: cols-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${APP_DATABASE_URL}
      AUTH_SECRET: ${APP_AUTH_SECRET}
      NEXTAUTH_URL: ${APP_URL}
      ALLOW_DEFAULT_SEED_USERS: ${APP_SEED_DEFAULT_USERS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cols-network

volumes:
  cols_pgdata:


networks:
  cols-network:
    driver: bridge
